server:
  host: "0.0.0.0"
  port: 8080

postgres:
  host: "postgres"
  port: 5432
  user: "highdolen"
  password: "ertz137"
  db: "metrics"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "5m"

